### ISSUE TITLE
Context menu items EPIC

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo#21]
### TODO:

- [x] Ability to mitigate all groups
- [x] Tracking of when widgets need to be added to context menu if their corresponding view becomes active
- [x] UI/UX for adding container widgets or other sorts of widgets
- [x] "Add to" button in editing ALL view; to allow creation of chatrooms, custom widgets, etc
- [x] Make 'about' widget special
- [x] Create widgets automatically when certain group creation events occur (custom view added, chat created)
- [x] STYLE MENU
- [ ] Allow widget titles to be edited
- [x] Do we do icons? Defaults, customizable, etc etc
- [x] Deeper look at members widget; what members do we want to return there and do we display badges? #210 
- [x] Make sure 'About' url works and port view if required
- [x] Create 'ask-and-offers' view, so that its url goes somewhere

MOBILE
- [x] clone mutations/query changes, etc
- [x] #153
- [x] #154

### Original Commentary

"ContextMenuWidgets": sections of the ContextMenu that display data and point to different views

Sources from the [product spec as of 22OCT24](https://docs.google.com/document/d/1KYN7HuTZpL_dPpSQxzCKYUG_FJAXAIEBxMVKaKXD0GM/edit?tab=t.0):
These things can be:
- Renamed from their default label (default label can be translated however => better for i18n)
- reordered
- added to and removed from the context menu (Are there any limits? There must be at least one? There must always be a 
 'home' section?)

##### Naming
~Section sounds like the container for these things in the html, as opposed to what they are. At a minimum, I'd prefer to refer to them as something more specific, like 'MenuSection'. If one searches 'section' in the repo, one gets lots of references to 'sections' in parts of the app that...~ 

Will work with them being called `ContextMenuWidget` for now

##### Requirements

Each `ContextMenuWidget` must have:
- a title/name
- a type
- variant (for 2nd phase)
- an order (I need to look at dnd-kit to understand its implementation)
- A way to define or connect to it's contents
- Their contents are not 'type' constrained; they can include a chat, a custom link (This is currently not supported by customviews, so might have to be punted)

Categories of `ContextMenuWidgets`
- single item (ungrouped): a direct link to a view. Similar to the prior Hylo menu items.
- grouped view list: A list of views. Each view has some activity indicators
- (?) grouped list, with platform additions: An ordered list that is editable but occasionally the platform appends something to
- grouped content list: A list of content. Links directly to that content, so we have to figure out whether it also renders a view underneath the content. If its a chat, than yes that chat room... for posts: since all group content could plausibly go into the general chat, perhaps it is just that.
- Special cases:  Map view, members view (includes an action), calendar

##### Running lists of them:
- member section (possibly several variants in the future) Basically a member list with an optional 'invite' button
- "what's going on?/¿que pasa?" section
- Chat section (for a list of chats) "What people are talking about"
- Map widget (2nd phase?) "Near you"
- Group list (list of groups) "Groups to join"
- Group steward widget "Grow your group" (Only viewable by stewards for now)
- Simple lists (content or views)
- Events (link and shows events happening in the next few days)
- Calendar (2nd)
- About section (points to Purpose, Group Agreements, a Custom post)
- Custom views
- Is the HOME view its own section?
- Legacy streams (projects, events, asks, offers, proposals, moderation actions)

### Architecture

Goal: We have to have UI/UX that makes the common things a group wants (or expect from prior experience) easy to access.

A ContextMenuWidget could point to:
- managed collection of things (can be ordered)
- queried collection of things (can be sorted)
- The above with special display or actions

Which things:
- content (posts, all types, including new ones like group-activities)
- groups
- members
- special views
- tracks (in future)
- custom views (many-to-many)

CustomViews (which point at: a collection of posts, a query/stream or an external link) cover some but not all of these needs...

Covering off on what we want to deliver in 1st phase:

Managed collections
- [x] Chats (managed collection, only chats)
- [x] About section (special display widget with optional collection)
- [x] 'Setup' Group steward widget (??? maybe a place to introduce actions?)

Queried collections
- [x] Member widget: list (queried collection plus invite button if you have req. responsibility)
- [ ] Recent activity (queried collection)
- [x] Group list (queried list)
- [ ] Events (queried collection with special display, if event is just about to happen)
- [ ] Proposals (queried collection with special display, if event is just about to happen)

Others
- [x] what's happening (lots of behavior questions)
- [x] Home section (single option)
- [x] Simple lists (custom views)

So thinking about how to model all of this; some options
Option A: model ContextMenuWidget in db; hard-code what to do with common views, point at custom views
Option B: model ContextMenuWidget in db; create CommonView to model the legacy views, point at custom views

**Leaning towards just doing Option A for now**

### UI/UX implementation
If we go crazy on multi layered dnd
https://www.reddit.com/r/reactjs/comments/16ogvr6/nested_sortable_lists_multiple_containers_with/

Only doing one layer of dnd (drag and drop) for phase one, for re-ordering widgets

### Tracking 'recent activity'
What needs to be included? What data is available? What counts as 'recent' for the number counts?
Going to punt on figuring this part out until we have the rest of the context menu pieces in place

**Comment by thomasgwatson** [comment]
TODO:

- [ ] Ability to mitigate all groups
- [ ] Tracking of when widgets need to be added to context menu if their corresponding view becomes active
- [ ] UI/UX for adding container widgets or other sorts of widgets
- [ ] Integration of custom view creation into menu editing (nice to have)
- [ ] Make about widget special
- [ ] Create widgets automatically when certain group creation events occur (custom view added, chat created)
- [ ] STYLE MENU

MOBILE
- [ ] clone mutations/query changes, etc
- [ ] implement UI
- [ ] Figure out if we skip or limit editing of menu on mobile

**Comment by thomasgwatson** [comment]
Rebalancing custom views and context widgets and chat rooms, as entities. (Following on from a chat with Tibet)

Context widgets are primarily touchpoints for users to be directed to something else on the platform. That 'something else' could be a post, a user, a group, a collection of those, a track, a stream, etc etc.

Custom views are a few different ways for users to define a specific slice of content. Currently this is an external url, a specific filtered stream, or a collection of posts

Chats have previously relied on the display of group-Topics to make them accessible, with the defacto outcome that all group topics have a chatroom. Since topics won't have the real place in the coming menu design, we have to define a way for chats to be accessible.

Tibet and I chatted about some of these concerns and these are a few of the notes I recall from the discussion:
- Chats could be modeled by creating a custom view to point at them, or to create a widget that points at a topic
- context widgets and custom views have some conceptual overlap, since they both have the attribute of 'pointing at other things'

One concept that was detailed was that the custom views that just point at a collection, or that just point at an external link, could be ported to context widgets and that the filters and query parameters of a customizable stream would be the core of custom views.

Conceptually, I think that does make total sense. And... if we decided to make that change, beyond the data migration, we would also have to reconfigure every part of the app that touches custom views, and make sure that the different views are still accessible. So its just a lot of touches

**Comment by tibetsprague** [comment]
Dang, meant to follow up here sooner. What I am leaning towards now is
- Create a new table/entity for chat rooms
- Custom views are only used for a custom filtered set of posts
- For external links and post collections we just have widget types that point to them

There really aren't many places custom views are used - just in the menu really. So this isn't a big change. 

The one place I still feel hung up is that I still believe that we should not be creating widgets for every possible thing that could go in the menu, and should only create them for things that are actually in the menu. I think creating widgets for everything will lead to a lot of extra messiness and need to deal with the database way more than necessary, as things continue to change in the future. Every time we change something in one of the other entities we may need to add, remove  or change existing widgets for every group in our database. I mean this could still be the case for widgets in the menu, but would mean many less widgets to deal with.
