### ISSUE TITLE
New Layout and Design framework

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo#43]
- [x] Full width design
- [x] New colors and components
- [ ] No more right sidebar
